### ISSUE TITLE
error running step 2

### ISSUE THREAD

**Issue by pradyumnasagar** [tf2/CNest#12]
when i try to run step 2 with the following command the CNest.py stops processing.
```
sudo docker run -v "/data/results/tools/CNest_Analysis:/input" -v "/data/results//tools/CNest_Analysis:/output" -w "/output" -it --rm \
    tomas81/cnest:dev step2 \
    --project test_proj \
    --sample 'bam' \
    --input sample.bam
```

we have the bam file in "/data/results/tools/CNest_Analysis/" the sequencing technique is single end sequencing in iontorrent. 

I got the following error message:

```
10/20/2022 13:13:01 | INFO: Start step2 for sample bam

10/20/2022 13:13:01 | ERROR: bam-to-rd failed with exit code -11.
b''
Traceback (most recent call last):
  File "/resources/cnest.py", line 355, in <module>
    step2(args.project, args.sample_id, args.input_file, args.debug)
  File "/resources/cnest.py", line 164, in step2
    if process2.returncode == 0:
UnboundLocalError: local variable 'process2' referenced before assignment

```

Please help me troubleshoot.
Thanks

**Comment by tf2** [comment]
Hi Pradyumna,

Sure - happy to help here...

First thing thing to check is that "chromosome tags" (i.e. chr1 vs 1) in
your BAM files and the "index" files are consistent.

Can you check and let me know - also are these BAMs human alignments or
something else?

Cheers,

Tom

**Comment by pradyumnasagar** [comment]
Hi thanks for helping, 
The BAM file consist of chromosome tag (with chr) and the index was created by samtools index function .
yes the BAM file is human alignment files.
